### ISSUE TITLE
Bug: Python 3.12 change breaks nbtedit

### ISSUE THREAD

**Issue by stragulus** [zzzeek/nbt2yaml#3]
``` 
File "/home/xxx/opt/nbt2yaml/lib/python3.12/site-packages/editor.py", line 11, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

Fix: ```from shutil import which``` and use which() instead

**Comment by stragulus** [comment]
This is actually an issue with dependency python-editor, which you haven't hard-pinned a specific version of, so not really a bug here.

**Comment by zzzeek** [comment]
I dont work with nbtedit anymore so you'd need to send a PR, i can cut a release

**Comment by zzzeek** [comment]
ok

**Comment by stragulus** [comment]
https://github.com/fmoo/python-editor/pull/39 fixed but not released yet FYI for like the 8th person to ever stumble upon this repo or bug ;)
